# Set update schedule for Maven dependencies

version: 2
updates:

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      # Check for updates to Maven dependencies every week
      interval: "weekly"